
wallpaper {
    monitor = DP-1
    path = /home/mahalo/photos/art7_adeptasororitas-nov14-5-ude5rm3tkl.jpg
    fit_mode = cover
}
 

wallpaper {
    monitor = DP-2
    path = /home/mahalo/photos/wallhaven-8ggqqj.jpg
    fit_mode = cover
}
 
splash = false