#main monitor
preload = $HOME/photos/wallhaven-jx77pq.jpg
#left
preload =$HOME/photos/wallhaven-5gvkr3.png

#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
wallpaper = DP-1,$HOME/photos/wallhaven-jx77pq.jpg
wallpaper = DP-2,$HOME/photos/wallhaven-5gvkr3.png

#enable splash text rendering over the wallpaper
splash = false

#fully disable ipc
# ipc = off
