#main monitor
preload = $HOME/photos/wallhaven-jx77pq.jpg
#left
preload =$HOME/photos/lessres/han-flores-dark-star-final-x-final-rs.jpg

#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
wallpaper = DP-4,$HOME/photos/wallhaven-jx77pq.jpg
wallpaper = DP-5,$HOME/photos/lessres/han-flores-dark-star-final-x-final-rs.jpg

#enable splash text rendering over the wallpaper
splash = false

#fully disable ipc
# ipc = off
